services:
  draft:
    image: ${DOCKER_REGISTRY-}draft
    build:
      context: .
      dockerfile: Draft/Dockerfile
    ports:
      - "5000:7080"
      - "5001:7081"
    depends_on:
      - postgres_db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Draft_proj
    volumes:
      - postgres-data:/var/lib/postgresql/data  
volumes:
  postgres-data: